markdown_extensions:
- meta
- admonition
- pymdownx.extra
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
nav:
- Home: index.md

site_name: Mkreports documentations
theme:
  custom_dir: docs/overrides
  name: material
