markdown_extensions:
- meta
- admonition
- pymdownx.extra
- pymdownx.details
- pymdownx.superfences
- pymdownx.snippets
- pymdownx.highlight:
    use_pygments: true
- pymdownx.tabbed:
    alternate_style: true
nav:
- Home: index.md
- Quickstart: quickstart.md
- Markdown: markdown.md
- Basic: basic.md
- Images: images.md
- Tables: tables.md
- Code Blocks: code_blocks.md
- Reference:
  - mkreports:
    - _stack: Reference/mkreports/_stack.md
    - code_context: Reference/mkreports/code_context.md
    - docs: Reference/mkreports/docs.md
    - exceptions: Reference/mkreports/exceptions.md
    - ipython: Reference/mkreports/ipython.md
    - md:
      - base: Reference/mkreports/md/base.md
      - combo: Reference/mkreports/md/combo.md
      - containers: Reference/mkreports/md/containers.md
      - docstring: Reference/mkreports/md/docstring.md
      - file: Reference/mkreports/md/file.md
      - header: Reference/mkreports/md/header.md
      - idstore: Reference/mkreports/md/idstore.md
      - image: Reference/mkreports/md/image.md
      - list: Reference/mkreports/md/list.md
      - settings: Reference/mkreports/md/settings.md
      - table: Reference/mkreports/md/table.md
      - text: Reference/mkreports/md/text.md
    - md_proxy: Reference/mkreports/md_proxy.md
    - parser: Reference/mkreports/parser.md
    - report: Reference/mkreports/report.md
    - settings: Reference/mkreports/settings.md
    - tracker: Reference/mkreports/tracker.md
    - utils: Reference/mkreports/utils.md
- Site Code:
  - Main: site_code/main.md
  - Basic: site_code/basic.md
  - '  Init  ': site_code/__init__.md
  - Images: site_code/images.md
  - Code Blocks: site_code/code_blocks.md
  - Tables: site_code/tables.md
  - Quickstart: site_code/quickstart.md
plugins:
- search
- mkdocstrings
site_name: Mkreports documentations
theme:
  custom_dir: overrides
  name: material
